### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by simahawk** [OCA/repo-maintainer-conf#31]
![image](https://github.com/user-attachments/assets/891694d9-b30a-447e-b012-1a7839ad6cae)

**Comment by etobella** [comment]
It is weird, because on the update repos va bien

![image](https://github.com/user-attachments/assets/cf0f4146-d310-4c05-84ca-04ffc6c7a907)

**Comment by simahawk** [comment]
Muchas gracias :)
