### ISSUE TITLE
Commit files' checksum

### ISSUE THREAD

**Issue by simahawk** [OCA/repo-maintainer-conf#4]
`OCA/repo-maintainer` is able to update repos and teams only if conf files have changed.
To do so, checksums must be computed and update on each conf update.

Consider using https://github.com/stefanzweifel/git-auto-commit-action

It likely caused #1

**Comment by etobella** [comment]
If you are comfortable with the action, I can create the PR :wink:

**Comment by simahawk** [comment]
> If you are comfortable with the action, I can create the PR 😉

In fact we don't need an action, we just need to stage the files and commit.
Yes, if you can take care of it go ahead. Otherwise I'll have a look tomorrow.

**Comment by etobella** [comment]
That action would make that :wink: So I will try to make it work

**Comment by etobella** [comment]
I added a commit directly and I think it works as expected :smile: s

a0a9d5bb54056aea4238f68d56ae571878723da6

He pushed the commit manually, so everything seems fine right now :smile: 

2a4222b677881ac1909344e02d433c03d1c2df8d

**Comment by simahawk** [comment]
Cool, tnx!

**Comment by simahawk** [comment]
I've just updated the README and merged. Here's the output of the action:

![image](https://github.com/OCA/repo-maintainer-conf/assets/347149/c51ca5d6-f373-447b-94d8-80e89cafd77f)


:tada:
