### ISSUE TITLE
Build v18 broken 

### ISSUE THREAD

**Issue by simahawk** [OCA/repo-maintainer-conf#44]
https://github.com/OCA/repo-maintainer-conf/actions/runs/11230387060/job/31217639829#step:5:89

TO BE CHECKED

**Comment by sbidoul** [comment]
Likely because https://github.com/OCA/runbot-addons/ is archived.

**Comment by SirAionTech** [comment]
> Likely because https://github.com/OCA/runbot-addons/ is archived.

Yes that's it https://github.com/OCA/repo-maintainer-conf/actions/runs/11230387060/job/31217639829#step:5:149:
> 2024-10-08 07:11:22,580 - oca_repo_maintainer.tools.manager - ERROR - command ['git', 'push', 'origin', 'HEAD'] in /tmp/tmpaoa2n2xi failed with return code 128 and output:
remote: This repository was archived so it is read-only.
fatal: unable to access 'https://github.com/OCA/runbot-addons/': The requested URL returned error: 403

**Comment by rousseldenis** [comment]
@simahawk Either we add an `active` parameter, either we remove (or archive) yaml file.

**Comment by sbidoul** [comment]
I'd remove `runbot.yml`

**Comment by simahawk** [comment]
On it
